### ISSUE TITLE
RFC: Create a futures-based version of ThetaGang?

### ISSUE THREAD

**Issue by brndnmtthws** [brndnmtthws/thetagang#164]
_Leaving this issue here as a request for comments. If I decide to get around to this, it probably won't happen for a while. Alternatively if you have a lot of money and want me to implement this, you can hire me (send me an email)._

I'm considering creating a futures version of this, which would allow you to specify a leverage ratio and use futures instead of stocks or ETFs to accomplish the same thing on major indices.

The main advantages of using futures rather than ETFs are that:

- they're slightly more efficient than using ETFs in most cases (i.e., lower fees)
- Bitcoin futures are available
- you can relatively easily obtain arbitrary leverage factors (up to the maximum leverage per the contract) if you have enough capital, with low costs
- futures are taxed at 60/40 long/short cap gains

The main downside of futures are that:

- the contracts are HUGE: the nominal value for the NASDAQ-100 is around $250k at the time of writing, so you'd need to set aside $250k to hold 1 contract and 20x that amount to write puts or calls
- option volume is not great, due to the massive size of the contracts
- you can never get 100% long term cap gains, you must roll the contract every quarter (or whatever the contract requires)

Thoughts?

**Comment by ggscott** [comment]
It is a good thought exercise and definitely worth the time to expand the code base if needed.  Couple of addl thoughts:

 depending on the brokerage house, leverage / margin is different on different future instruments. So unless you’re doing (like you mention below) a fully secured contract - leverage on each different contract will need to be taken into account
price / liquidity manipulation of the underlying future is rampant when the volume is low - so there may need to be safety breakers (much like low volume options, just saying) - not so much on the currently active majors like /ES&/CL but when you hold after the volume moves to the next active month it could be a concern
