### ISSUE TITLE
Add error checking if gateway/client already open

### ISSUE THREAD

**Issue by talso** [brndnmtthws/thetagang#166]
I've already launched my full client via IBCLinux/twsstart.sh, can you add a check to see if the gateway is reachable/working before launching the client again?

**Comment by brndnmtthws** [comment]
The gateway is managed by the script (i.e., it's started when you start the script). Why not just close it and then run the script?

It would require code changes to do what you ask, and at the moment I don't plan on doing it. You're welcome to submit a PR though. I'll leave this issue open.
