### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by tkschuler** [brndnmtthws/thetagang#168]
`pip install thetagang ` is not working for me.  Also, without a setup.py file, I'm not sure how to install from source

**Comment by brndnmtthws** [comment]
What version of Python are you using? Currently only >=3.8 is supported.

**Comment by tkschuler** [comment]
Thanks for the update.  I am using Python 3.6

**Comment by brndnmtthws** [comment]
If you want to try it with 3.6 (don't know if it'll work, haven't tested) you can install [Poetry](https://python-poetry.org/) and do a `poetry install` then `poetry run thetagang` to test it out.
