### ISSUE TITLE
One final request and everything should be good.

### ISSUE THREAD

**Issue by Ianfinn1994** [brndnmtthws/thetagang#170]
Sorry for the delay boss, just got home. I ran the code you sent and got this output. 

delos@DESKTOP-087HUSE:~/thetagang$  docker run --rm -it \
>     -v ~/thetagang:/etc/thetagang \
>     brndnmtthws/thetagang:latest \
>     --config /etc/thetagang/thetagang.toml
+ export DISPLAY=:1
+ DISPLAY=:1
+ Xvfb :1 -ac -screen 0 1024x768x24
+ exec poetry run thetagang --config /etc/thetagang/thetagang.toml

Config:

  Account details:
    Number                   = DU2275067
    Cancel existing orders   = True
    Margin usage             = 0.3 (30.0%)
    Market data type         = 1

  Roll options when either condition is true:
    Days to expiry          <= 15
    P&L                     >= 0.9 (90.0%)

  Write options with targets of:
    Days to expiry          >= 45
    Delta                   <= 0.3
    Minimum open interest   >= 10

  Symbols:
    GLD, weight = 0.4 (40.0%)
    TECL, weight = 0.3 (30.0%)
    SLV, weight = 0.3 (30.0%)

My info is there, user id and all, no param for password except here.

[ibc]
# IBC configuration parameters. See
# https://ib-insync.readthedocs.io/api.html#ibc for details.
gateway     = true
ibcPath     = '/opt/ibc'
password    = 'demo'
tradingMode = 'paper'
userid      = 'demo'
# Change this to point to your config.ini for IBC
ibcIni = '/etc/thetagang/config.ini'

Do i fill this out too boss, including the path to where anything may be installedc, or is the bot running and does it self populate it all? Its probably because markets are closed that its not running fully?

**Comment by brndnmtthws** [comment]
I don't quite understand your question, but I'll try to answer.

You need to supply `config.ini`, which is the configuration file that controls IBC (which is the tool for running Trader Workstation, yes I know it's a lot of stuff). There is a sample `config.ini` [located here](https://github.com/brndnmtthws/thetagang/blob/main/ibc-config.ini).

You can copy the sample `config.ini` and everything _should_ work, but there may be instances where you want to change the parameters. For that, it is up to you.

**Comment by Ianfinn1994** [comment]
Everything runs and my terminal is populated by blue writing with the params from thetagang.toml, (so i assume its working right), buts its not placing any orders.

**Comment by brndnmtthws** [comment]
How long did you let it run for? It can be a bit slow when scanning the options chains, for example.

Additionally, it won't do anything unless you have adequate funds available. For example, to write 1 put on GLD at 0.3 delta you'd need $167 (strike price) x 100 shares, which is $16,700 of required maintenance margin.

**Comment by Ianfinn1994** [comment]
In the demo account boss, i have like 20 k.

**Comment by brndnmtthws** [comment]
20k won't be enough, you've set the margin usage at 0.3 so it'll only use 0.3 * $20k which is $6k.

Additionally, that amount is divided amongst the symbols you specify, so to take a simple example if you had a 50/50 split of 2 symbols that needed $10k each to purchase, you would need $20k available to write 1 put on each.

**Comment by Ianfinn1994** [comment]
I will try something cheaper right now.

**Comment by brndnmtthws** [comment]
If you just want to do it for test purposes, you can try just SLV (which has a relatively low price) and set its weight to 1.0, comment out the other 2.

**Comment by foolish-dev** [comment]
I would like to mention that GitHub is not a forum and issues should not be used like this 🤷‍♂️

**Comment by brndnmtthws** [comment]
> I would like to mention that GitHub is not a forum and issues should not be used like this 🤷‍♂️

The issue is completely on topic and relevant. If one person has a problem, it's likely someone else may have the same problem.

**Comment by Ianfinn1994** [comment]
I had commented the others out and adjusted the weight. Also maxed out the margin. It is running and on the bottom the cursor box is flashing so maybe i will let it run for awhile. I dont have to have IBKR or anything else installed on my pc? Or have to connect to any host at all? If not ill just let it sit and run for awhile and see what happens.

**Comment by brndnmtthws** [comment]
You should check the IBC log to see if there's anything relevant. You may need to change the path here:

https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L89

Set it to something like `/etc/thetagang/ibc.log` then you can access it at `~/thetagang/ibc.log`.

It should at the very least be printing your balances from IB. If you aren't seeing that, it's probably not actually connecting. Double check that you can login using Trader Workstation (without using ThetaGang) if you haven't already.

**Comment by Ianfinn1994** [comment]
would i need to change these other variables as well? 


https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L94
https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L95
https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L96
https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L98

**Comment by brndnmtthws** [comment]
You need to change the username, password, and trading mode depending on whether you want to use a paper account or a real account.

**Comment by Ianfinn1994** [comment]
Yeah its still not loading the chain. I had set silver to 1.0 and it has just stayed on the basic screen. Maybe one of my directories is wrong? Also what about 
https://github.com/brndnmtthws/thetagang/blob/main/thetagang.toml#L100.

**Comment by brndnmtthws** [comment]
The ibcini path should be fine. Check the log file, it should contain something useful. Also keep in mind it doesn't really work properly outside normal market hours. If you change the market data type to 4 ([see here](https://interactivebrokers.github.io/tws-api/market_data_type.html) it will sort of work for testing purposes, but make sure to change it back to 1.

**Comment by Ianfinn1994** [comment]
I had changed everything and its still just running and not fetching any market data. I had set it to 4 just like you said as well. I even switched the computer I'm using to my MacBook to make things easier, but Like you had stated, maybe its due to it being the weekend.

**Comment by cakkineni** [comment]
@brndnmtthws  thank you for making this available (and as a docker image...very much appreciated) 

I had the same initial issues like you, but making progress (I think):

this is what i did: I setup a demo account and switched to those details [(like what you've listed here)](https://github.com/brndnmtthws/thetagang/issues/170#issuecomment-769975166), used a beefier machine (switched to a 8-core linux vm); your mac should be fine. 

  Account details:
    Number                   = xxxxxxxxxxx
    Cancel existing orders   = True
    Margin usage             = 0.5 (50.0%)
    Market data type         = 4

  Roll options when either condition is true:
    Days to expiry          <= 15
    P&L                     >= 0.9 (90.0%)

  Write options with targets of:
    Days to expiry          >= 45
    Delta                   <= 0.3
    Minimum open interest   >= 10

  Symbols:
    SLV, weight = 1.0 (100.0%)


Account summary:

  Excess liquidity  =   1000000.00
  Net liquidation   =   1000000.00
  Cushion           = 1 (100.0%)
  Full maint margin =         0.00
  Buying power      =   4000000.00
  Total cash value  =   1000000.00

Portfolio positions:


Checking positions...


0 puts will be rolled


0 calls will be rolled


Total buying power: $500000 at 50.0% margin usage
Total value: $500000

  SLV
    Current position quantity 0
    Target value $500000.0
    Target quantity 20226
    Target additional quantity (excl. existing options) 20226

Preparing to write additional 202 puts to purchase SLV

Searching option chain for symbol=SLV right=P, this can take a while...

**Comment by brndnmtthws** [comment]
If you have the market data set to 4 it'll use frozen data (i.e., the last known values) so it should at least print stuff out. You should check the log to see what's happening.

**Comment by Ianfinn1994** [comment]
You said to edit the params in 
https://github.com/brndnmtthws/thetagang/blob/main/ibc-config.ini#L79
https://github.com/brndnmtthws/thetagang/blob/main/ibc-config.ini#L187
for demo and my username and password?

**Comment by cakkineni** [comment]
thats what i did; not sure if thats needed or not. its still trying to get market data (I've it set to 4). We should try it on monday and see I guess.

**Comment by Ianfinn1994** [comment]
yea hahaha. Maybe they are updating the system.

**Comment by brndnmtthws** [comment]
If you're trying to use a paper trading account (which is how you should first test it), you need to create the account and get the username and password and put that into the config. There is no such thing as a "demo" user, that's just a placeholder for the config file. You need a real account, either a paper account or a live account.

**Comment by Ianfinn1994** [comment]
I filled that in boss. Everything is filled in. My username and password on both pieces of code.

**Comment by Ianfinn1994** [comment]
2021-02-01 06:57:33,938 ib_insync.client ERROR API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4002)")
. Found this in the IB file. Will attempt more rigorous debugging.

**Comment by Ianfinn1994** [comment]
Do you need to install TWS, or is it populated in the Docker File?

**Comment by Ianfinn1994** [comment]
So basically, because I have IBKR lite, I can't access market data at all. I have to make a new account.

**Comment by Ianfinn1994** [comment]
I got the bot to work, but I'm getting memory errors. 

Java HotSpot(TM) 64-Bit Server VM warning:. something about not enough memory.

**Comment by brndnmtthws** [comment]
Try increasing the memory allocated to the Docker VM, from within the Docker settings. I think the default JVM heap size is 768m (`-Xmx768m`), but maybe if your VM is too small it'll be wrong.

**Comment by Ianfinn1994** [comment]
I was just using windows Wsl2.

**Comment by brndnmtthws** [comment]
I think WSL2 still has some memory limits: https://itnext.io/wsl2-tips-limit-cpu-memory-when-using-docker-c022535faf6f

Not an expert on it.

Anyway, glad to hear you got it sorted out. Please create a new issue if you run into problems.
