### ISSUE TITLE
Issue on Ubuntu Mate. 

### ISSUE THREAD

**Issue by Ianfinn1994** [brndnmtthws/thetagang#172]
Want to run it on my Raspberry Pi and have the crontab execute every 10 minutes. Getting this issue when building the image. 

standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size.

How could this error be rectified? Everything else is cool on the windows version.

**Comment by brndnmtthws** [comment]
Currently only amd64 is supported, not ARM.

In theory you should be able to get it working on ARM, given it's just a Java app, but I haven't tried.

If you want to try it yourself, you can build the Docker image locally (on your rasppi) and see if it works. Most likely it will fail, because we're currently using the bundled JVM instead of installing OpenJDK 8.

**Comment by brndnmtthws** [comment]
Digging a little more into it, they do some really weird stuff in the TWS installer. Not only do they try and force a specific version of the JVM, but they also pin it to amd64. I think it can be overridden, but it requires modifying the installer. or bypassing it altogether.

**Comment by brndnmtthws** [comment]
Honestly, this whole installer is a massive dumpster fire. One option is to extract the files and copy the jars out manually from an amd64 machine.

I hope IBKR hires some engineers who know what they're doing some day.

**Comment by brndnmtthws** [comment]
Okay, after a lot of futzing about I think I have something that works with 08e20bd240cf6bd358b1067304913e71af3743a9. Assuming the Docker build succeeds, you can try the latest now on your rasppi.

**Comment by Ianfinn1994** [comment]
wow thank you so much man

**Comment by brndnmtthws** [comment]
> also yea its like they dont want the little people to make money.

The name of the game is to get the money out of your pocket and into theirs.

**Comment by Ianfinn1994** [comment]
Also boss, can I try this again on Ubuntu mate? I know the error has to do with the pi's processor. The docker build was successful on raspberry picks until the processor error came up. Is there any way to recompile the code using a compiler for the pi? I can figure it out just like I sort of did with this project. Or should I keep trying with pi os?

**Comment by brndnmtthws** [comment]
The image is available for arm now, do a `docker pull brndnmtthws/thetagang:latest` and it'll work.

**Comment by Ianfinn1994** [comment]
Thank you sir

**Comment by Ianfinn1994** [comment]
pi@delos:~/thetagang $ docker run --rm -i -v ~/thetagang:/etc/thetagang brndnmtthws/theta
gang:latest --config /etc/thetagang/thetagang.toml
Unable to find image 'brndnmtthws/thetagang:latest' locally
latest: Pulling from brndnmtthws/thetagang
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.

**Comment by brndnmtthws** [comment]
I didn't realize Pi OS was still 32 bit. I had a really tough time getting the armv7 OpenJDK working properly so I dropped it. Let my try something else.

Pi OS does have a aarch64 release, but it says they don't recommend using it for some reason.

**Comment by Ianfinn1994** [comment]
It may be on the raspberry pi os? Yea i have an older pie that i put together with a GPIO fan and heat syncs. I want to have it run 247 with my IBKR stuff. You are a boss Brendan. Thank you very much. If you cant get it to work, ill try this raspberry image you suggested.

**Comment by brndnmtthws** [comment]
Here you go:

<img width="1275" alt="Screen Shot 2021-02-05 at 2 34 38 PM" src="https://user-images.githubusercontent.com/3129093/107086295-6a041900-67bf-11eb-80fd-bd9cdd3907b0.png">

Should work on both 32/64 bit arm.

**Comment by Ianfinn1994** [comment]
YAAAY!!! thank you!!!

I compiled everything on my pi and it was working. I keep getting this error call in the sync log. 

2021-02-05 18:48:31,034 ib_insync.client ERROR API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4002)")
2021-02-05 18:48:31,034 ib_insync.client ERROR Make sure API port on TWS/IBG is open

Ill try updating my systems copy to the image you just published. See if that corrects the error. Thank you so much again boss, this has been such a huge eye opener. Ive learned a decent amount about coding thanks to this project.

**Comment by brndnmtthws** [comment]
> 2021-02-05 18:48:31,034 ib_insync.client ERROR API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4002)")
> 2021-02-05 18:48:31,034 ib_insync.client ERROR Make sure API port on TWS/IBG is open
> 

There could be a lot of things causing this. Most likely, for some reason, TWS is not launching properly. I've tested on aarch64, and it does work, but I don't have an armhf machine to test with right now.

**Comment by Ianfinn1994** [comment]
I used raspberry pi os.

**Comment by Ianfinn1994** [comment]
I installed the new docker image and tried to run it. Noticed you added a minimum pnl variable. How do i set it to 50%? 0.5?

**Comment by brndnmtthws** [comment]
It should be a float. 1.0 is 100%, 0 is 0%, 0.5 is 50%. I meant to make that value optional, that was a mistake.

I might change the behaviour of that too. I'm worried about the case where you sell covered calls, and they end up deep ITM. Currently my preference is to roll them, but that may result in margin getting eaten up if they're grossly mispriced. If the P&L is something like -100%, you'd have to set that value to -1 for them to be rolled.

**Comment by Ianfinn1994** [comment]
that makes sense.

**Comment by Ianfinn1994** [comment]
I had tried to put 1.0 in and its still returning errors. 

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/schema.py", line 394, in validate
    nvalue = Schema(svalue, error=e, ignore_extra_keys=i).validate(value)
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/schema.py", line 415, in validate
    raise SchemaWrongKeyError(message, e)
schema.SchemaWrongKeyError: Wrong key 'min_pnl' in {'pnl': 0.9, 'dte': 15, 'min_pnl': -1.0, 'calls': {'itm': True}, 'puts': {'itm': False}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/src/thetagang/main.py", line 35, in cli
    start(config)
  File "/src/thetagang/thetagang.py", line 33, in start
    validate_config(config)
  File "/src/thetagang/config.py", line 98, in validate_config
    schema.validate(config)
  File "/root/.cache/pypoetry/virtualenvs/thetagang-VsnhxLU2-py3.8/lib/python3.8/site-packages/schema.py", line 398, in validate
    raise SchemaError([message] + x.autos, [e] + x.errors)
schema.SchemaError: Key 'roll_when' error:
Wrong key 'min_pnl' in {'pnl': 0.9, 'dte': 15, 'min_pnl': -1.0, 'calls': {'itm': True}, 'puts': {'itm': False}}

**Comment by brndnmtthws** [comment]
The newest image hasn't been published yet, you'll have to wait a while for it to finish.

**Comment by Ianfinn1994** [comment]
Ok boss

**Comment by Ianfinn1994** [comment]
Hey Boss, i had been messing with the code and noticed the new commits. Had tried to run it again and gave the float error for -1 

Key 'min_pnl' error:
-1 should be instance of 'float'

**Comment by Ianfinn1994** [comment]
-0.1 works great. The code freezes on  the screen and I think it's an issue with the port for ibkr or the domain (127.....) pardon my vernacular if my verbiage is wrong. Like I said, new to code and this is really good teaching me!

**Comment by Ianfinn1994** [comment]
How goes the new image, boss?

**Comment by brndnmtthws** [comment]
The image is available, and it should work on both armv7 and aarch64/armv8.

**Comment by Ianfinn1994** [comment]
Thank you sir, I'll try it out and let you know.

**Comment by Ianfinn1994** [comment]
2021-02-10 20:30:48,422 ib_insync.client INFO Connecting to 127.0.0.1:4002 with clientId 1...
2021-02-10 20:30:48,431 ib_insync.client INFO Disconnecting
2021-02-10 20:30:48,432 ib_insync.client ERROR API connection failed: ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4002)")
2021-02-10 20:30:48,432 ib_insync.client ERROR Make sure API port on TWS/IBG is open
2021-02-10 20:30:48,433 ib_insync.IBC INFO Terminating
2021-02-10 20:30:50,855 ib_insync.IBC INFO Starting
