### ISSUE TITLE
class diagrams and use cases 

### ISSUE THREAD

**Issue by ALT-KIK** [brndnmtthws/thetagang#174]
I am University student and my job is to make class diagrams and uses cases for some project. I chose this project and can make it. Ofc if you need it.
If you think that you don't need it now, I can make SRS document for the project. Also, if you need ofc.
What is SRS document: https://en.wikipedia.org/wiki/Software_requirements_specification

**Comment by brndnmtthws** [comment]
Yeah that would be cool. If you'd like to create an Architecture.md and add that in a PR, that'd be a great start. Here's a good example (although this level of detail isn't required): https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/architecture.md

**Comment by ALT-KIK** [comment]
I wanted to notify you that I am going to do this, so do not close the issue please.
