### ISSUE TITLE
only support USD currency

### ISSUE THREAD

**Issue by junyuanz1** [brndnmtthws/thetagang#267]
Hi @brndnmtthws ,

I saw USD is hard coded in multiple different places. I want to help and make this currency optional.

The easiest solution would be user can create multiple configuration files for different currencies. If that sounds good, I can help implement this change.

Thanks,

Junyuan

**Comment by brndnmtthws** [comment]
I'd be happy to add this feature, it just needs to be implemented such that it remains backward-compatible.
