### ISSUE TITLE
Position not rolled - conditions met

### ISSUE THREAD

**Issue by robby28-11** [brndnmtthws/thetagang#387]
Currently have a position that is just ITM but with a positive P&L. Still not beeing rolled.

> `│ │     Roll options when                                                      │
│ │     either condition is                                                    │
│ │     true                                                                   │
│ │                           Days to expiry        <=   15 and P&L >= 0.0     │
│ │                                                      (0%)        `

____

>  SBUX │  │    │      │      │      │     │      │     │      │     │    │     │
│      │P │ -1 │$0.85 │$0.93 │ $-85 │$-93 │   $8 │9.0% │$92.… │202… │  3 │✔️    │
└──────┴──┴────┴──────┴──────┴──────┴─────┴──────┴─────┴──────┴─────┴────┴─────┘

_____

0 puts can be rolled 

Full log in the attachment.

[SBUX_NoRoll.txt](https://github.com/brndnmtthws/thetagang/files/14654991/SBUX_NoRoll.txt)

**Comment by brndnmtthws** [comment]
Set `roll_when.puts.itm = true`. See:

https://github.com/brndnmtthws/thetagang/blob/cdea558ce00ca5a1de95f282ca59bfb742638b76/thetagang.toml#L165-L167

By default, it won't roll an ITM put.

**Comment by robby28-11** [comment]
Sorry, my bad.

Now it is working of course.
