### ISSUE TITLE
Change from ib_insync to ib_async

### ISSUE THREAD

**Issue by laroche** [brndnmtthws/thetagang#403]
Seems author of ib_insync has died recently and the project is now
maintained as https://github.com/ib-api-reloaded/ib_async.

Can you please check if it makes sense to change over to this new
IB API lib?

best regards and thanks a lot for "thetagang",

Florian La Roche

**Comment by brndnmtthws** [comment]
I have looked into it, and there doesn't seem to be any new features (yet) so I'll hold off on making the change until there's a good reason for it.

**Comment by brndnmtthws** [comment]
See also https://github.com/brndnmtthws/thetagang/discussions/382
