### ISSUE TITLE
Setting DTE per symbol in toml 

### ISSUE THREAD

**Issue by noamagiv** [brndnmtthws/thetagang#425]
Hi,
I would like to set individual DTE per symbol, getting an error while setting DTE under symbols in TOML configuration.
is there any way to configure this? 

Thanks !

**Comment by brndnmtthws** [comment]
Not currently possible, but this should be easy to add.

**Comment by noamagiv** [comment]
I can try.... do you want to assign it to me?

**Comment by noamagiv** [comment]
Done in PR #428
