### ISSUE TITLE
Write_when Green and red bug, sending "C" to is_ok_to_write_puts function

### ISSUE THREAD

**Issue by noamagiv** [brndnmtthws/thetagang#429]
def is_ok_to_write_puts(
                symbol: str,
                ticker: Ticker,
                puts_to_write: int,
            ) -> bool:
                if puts_to_write <= 0:
                    return False

                (can_write_when_green, can_write_when_red) = can_write_when(
                    self.config, symbol, "C"
                )

**Comment by noamagiv** [comment]
you can assign this and 427 to me if you want:)

**Comment by brndnmtthws** [comment]
Nice catch, thanks. Already made a PR for this.
